import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ url }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello Your URl is : {url}
    </div>
  );
}

export async function getServerSideProps(context) {
  const url = context.req.url;

  return {
    props: {
      url: url,
    },
  };
}
